### ISSUE TITLE
com.sun.awt.AWTUtilities has apparently been removed

### ISSUE THREAD

**Issue by jameswestman** [TechnicPack/LauncherUICore#8]
com.sun.awt.AWTUtilities [has apparently been removed in JDK 11](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8201219). This means Technic will not run on the latest JDK (I am testing with openJDK).

According to [this bug](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8200149) all its functionality is available elsewhere in the public API, though I haven't yet found where. At the very least, though, a java.lang.NoClassDefFoundError needs to be caught [here in the SplashScreen class](https://github.com/TechnicPack/LauncherUICore/blob/master/src/main/java/net/technicpack/ui/controls/installation/SplashScreen.java#L84).

**Comment by Pyker** [comment]
Thank you for your bug report!
